version: '3'
services:
  app:
    image: mascotas-app
    build:
      context: .
    ports:
      - "8091:8091"
    environment: 
      - spring.datasource.url=jdbc:oracle:thin:@bdejercicios_tp?TNS_ADMIN=/app/wallet
      - spring.datasource.username=FSI_SUMATIVA2
      - spring.datasource.password=FSI-Sumativa2
      - spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
      - spring.jpa.hibernate.ddl-auto=update

      - SPRING_JPA_SHOW_SQL=true
      - TNS_ADMIN=/app/wallet
    networks:
      - default

networks:
  default:
    driver: bridge

      # - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@bdejercicios_tp?TNS_ADMIN=wallet
      # - SPRING_DATASOURCE_USERNAME=FSI_SUMATIVA2
      # - SPRING_DATASOURCE_PASSWORD=FSI-Sumativa2
      # - SPRING_DATASOURCE_DRIVER_CLASS_NAME=oracle.jdbc.driver.OracleDriver
      # - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect